/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * ESLint for the suite.
 *
 * ## Why this exists
 *
 * Until 2026-09-20 `npm run lint` was `tsc --noEmit` and nothing else. That
 * catches type errors and nothing about stale React hook dependencies, unused
 * bindings, or a `case` that falls through. Those are the defects that produce
 * a wrong answer rather than a crash, which is the failure mode this repo cares
 * about most (`CLAUDE.md`, data provenance).
 *
 * ## What is switched on, and what deliberately is not
 *
 * This is a **correctness** configuration, not a style one. The repo has 60k+
 * lines written without a linter; turning on a full recommended set would bury
 * real findings under thousands of cosmetic ones and invite a mass auto-fix
 * across code nobody is currently reading. So:
 *
 *   - Rules that find likely BUGS are errors.
 *   - Rules that express taste are off. Formatting is not litigated here.
 *   - `react-hooks/exhaustive-deps` is an **error**, not the usual warning.
 *     A stale closure over workspace state is exactly how this app would show a
 *     coach last workspace's numbers, and a warning nobody sees is not a guard.
 *
 * Generated and vendored output is ignored, including the extension bundles,
 * which have their own guard in `tests/swimCloudExtensionBuildFreshness.test.ts`.
 */
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      'test-results/**',
      'venv/**',
      'src-tauri/**',
      'omniswim-suite/**',
      // Generated by extensions/swimcloud-companion/build.mjs. Guarded by a
      // freshness test instead; linting a bundle reports the bundler's style.
      'extensions/swimcloud-companion/crawler.js',
      'extensions/swimcloud-companion/background.js',
      'public/**',
      'data/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      /* ---- Real defects -------------------------------------------------- */

      // The headline rule. A missing dependency silently serves stale state.
      'react-hooks/exhaustive-deps': 'error',
      'react-hooks/rules-of-hooks': 'error',

      // `==` against null is the idiom this codebase uses deliberately to mean
      // "null or undefined", so allow exactly that and require === elsewhere.
      eqeqeq: ['error', 'always', { null: 'ignore' }],

      'no-fallthrough': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-constant-binary-expression': 'error',
      'no-self-compare': 'error',
      'no-template-curly-in-string': 'error',
      'no-unmodified-loop-condition': 'error',
      // Off, deliberately. Every finding it produced in this repo was the same
      // false positive: assigning to a per-request or module-local binding after
      // an `await`, where no second caller exists to race with. Express handlers
      // own their `req`, and the crawler's pacer (`fetchPageWithDelay`) is the
      // single sequential caller of its own timestamp -- the pooled swimmer-times
      // path deliberately bypasses it (see boundedFetchPool.ts). Leaving the rule
      // on would mean eight suppressions saying the same thing.
      'require-atomic-updates': 'off',
      'array-callback-return': ['error', { allowImplicit: false }],

      // `await` in a loop is often correct here on purpose: the crawler paces
      // requests, and parallelising it is exactly what must not happen.
      'no-await-in-loop': 'off',

      /* ---- Unused code --------------------------------------------------- */

      'no-unused-vars': 'off', // superseded by the TS-aware version
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          // A deliberately-ignored catch binding is idiomatic in this repo's
          // best-effort paths (backups, cache reads); name it `_err` to say so.
          ignoreRestSiblings: true,
        },
      ],

      /* ---- Taste, deliberately off --------------------------------------- */

      // `any` appears in parser and HTTP boundary code where the shape is
      // genuinely unknown until validated. The repo's answer to that is a
      // runtime validator, not a type assertion, and that is reviewed by hand.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      // `destructuring: 'all'` so a `let { h, s, l } = ...` is not flagged just
      // because one of the three is never reassigned -- you cannot split a
      // destructuring pattern across const and let.
      'prefer-const': ['error', { destructuring: 'all' }],
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },

  // The extension runs as a Manifest V3 content script / service worker, so
  // `chrome` is ambient. The TypeScript sources declare it in chrome-shim.d.ts;
  // the two plain .js files have no such declaration to read.
  {
    files: ['extensions/swimcloud-companion/**/*.js', 'extensions/swimcloud-companion/**/*.ts'],
    languageOptions: { globals: { chrome: 'readonly' } },
  },

  // Tests and scripts run in Node and legitimately do things app code must not.
  {
    files: ['tests/**/*.ts', 'scripts/**/*.mjs', 'scripts/**/*.ts', '**/*.config.*', '**/build*.mjs'],
    languageOptions: { globals: { ...globals.node } },
    rules: {
      '@typescript-eslint/no-unused-expressions': 'off',
      // Test scripts shim browser globals and load CommonJS fixtures; both are
      // legitimate there and neither ships.
      '@typescript-eslint/no-this-alias': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
);
