/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * The capture id has exactly one definition, and every consumer agrees on it.
 *
 * ## What went wrong
 *
 * `extensions/swimcloud-companion/background.js` used to carry a hand-written
 * `captureIdGuess(subject)` beside `captureStore.ts`'s `captureIdForSubject`.
 * The two agreed only by construction — team-subject crawls are not
 * implemented, so the season branch was never exercised by anything. Had the
 * real rule changed, every `POST /api/swimcloud/captures/{id}/pages` from the
 * extension would have targeted a capture id nobody opened: a 404, a silent
 * fall-through to `chrome.downloads`, no server-store integration, and nothing
 * to notice.
 *
 * The duplication is now gone structurally — the rule lives in
 * `packages/swimcloud/src/entities.ts` (Node-free, so a browser bundle can
 * import it), `captureStore.ts` re-exports it, and `build.mjs` bundles the
 * worker from `src/background.ts`. These tests hold that shape in place: they
 * fail if the two exports ever become separate functions again, and they fail
 * if the worker source goes back to deriving the id by hand.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { captureIdForSubject as fromEntities } from '../packages/swimcloud/src/entities.ts';
import type { SwimCloudCaptureSubject } from '../packages/swimcloud/src/entities.ts';
import { captureIdForSubject as fromCaptureStore } from '../packages/swimcloud/src/captureStore.ts';
import { captureIdForSubject as fromPackageRoot } from '../packages/swimcloud/src/index.ts';
import { SWIMCLOUD_CAPTURE_ID_PATTERN } from '../apps/shell/lib/swimcloudCaptureRoutes.ts';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const backgroundSource = fs.readFileSync(
  path.join(repoRoot, 'extensions/swimcloud-companion/src/background.ts'),
  'utf8',
);

/** Every subject shape the id rule has a branch for, including the season branch nothing exercises yet. */
const SUBJECTS: ReadonlyArray<{ subject: SwimCloudCaptureSubject; expected: string }> = [
  { subject: { kind: 'meet', meetId: '356467' }, expected: 'meet-356467' },
  { subject: { kind: 'meet', meetId: '1' }, expected: 'meet-1' },
  { subject: { kind: 'team', teamId: '58' }, expected: 'team-58' },
  { subject: { kind: 'team', teamId: '633' }, expected: 'team-633' },
  { subject: { kind: 'team', teamId: '58', season: '2026-2027' }, expected: 'team-58-2026-2027' },
  { subject: { kind: 'team', teamId: '58', season: undefined }, expected: 'team-58' },
];

describe('captureIdForSubject — one definition', () => {
  it('is literally the same function everywhere it is exported', () => {
    // Not "produces equal output" — the same object. That is what makes drift
    // impossible rather than merely detectable.
    expect(fromCaptureStore).toBe(fromEntities);
    expect(fromPackageRoot).toBe(fromEntities);
  });

  it.each(SUBJECTS)('derives $expected', ({ subject, expected }) => {
    expect(fromEntities(subject)).toBe(expected);
    expect(fromCaptureStore(subject)).toBe(expected);
  });

  it('emits only ids the capture routes accept', () => {
    // A derived id that the route rejects would 400 every page POST, which is
    // the same outage as a mismatched id by a different door.
    for (const { subject } of SUBJECTS) {
      expect(SWIMCLOUD_CAPTURE_ID_PATTERN.test(fromEntities(subject))).toBe(true);
    }
  });

  it('never collides across the meet and team namespaces', () => {
    const ids = SUBJECTS.map(({ subject }) => fromEntities(subject));
    // `team-58` appears twice on purpose (season omitted vs. explicitly
    // undefined are the same subject), so compare against the distinct
    // subjects rather than the raw list length.
    expect(fromEntities({ kind: 'meet', meetId: '58' })).not.toBe(fromEntities({ kind: 'team', teamId: '58' }));
    expect(new Set(ids).size).toBe(5);
  });
});

describe('the extension worker uses that one definition', () => {
  it('imports captureIdForSubject from the Node-free module', () => {
    expect(backgroundSource).toMatch(
      /import\s*\{[^}]*\bcaptureIdForSubject\b[^}]*\}\s*from\s*'@omniswim\/swimcloud\/entities'/,
    );
  });

  it('declares no second capture-id derivation of its own', () => {
    expect(backgroundSource).not.toMatch(/function\s+captureIdGuess/);
    // The only place a capture id is spelled out is the imported function; the
    // worker must never rebuild one from template literals.
    expect(backgroundSource).not.toMatch(/`meet-\$\{/);
    expect(backgroundSource).not.toMatch(/`team-\$\{/);
  });

  it('is a build artifact of that source, not a hand-edited file', () => {
    // `background.js` is generated by build.mjs now. If someone edits the
    // bundle directly the banner survives but the rule would drift again, so
    // the bundle is checked for the inlined definition it must contain.
    const bundle = fs.readFileSync(
      path.join(repoRoot, 'extensions/swimcloud-companion/background.js'),
      'utf8',
    );
    expect(bundle).toContain('GENERATED by extensions/swimcloud-companion/build.mjs');
    expect(bundle).toContain('function captureIdForSubject');
  });
});
