/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Typed loader over the generated qualifying-standard tables.
 *
 * **There is not one competition value in this file, and there must never be.**
 * Every number comes from `data/cutlines/<season>.json`, which is generated by
 * `scripts/extract-cutlines.py` from the PDFs archived under
 * `data/cutlines/sources/` and pinned by sha256 in their `manifest.json`.
 * To change a standard you re-fetch and re-extract; you never edit TypeScript.
 *
 * The four governing bodies publish four genuinely different table shapes, so
 * the model is a discriminated union rather than one flattened row type:
 *
 * | Division | Individual        | Relay                    | Course        |
 * | -------- | ----------------- | ------------------------ | ------------- |
 * | D1       | single `standard` | qualifying + provisional | SCY           |
 * | D2       | A + B             | provisional only         | SCY           |
 * | D3       | A + B + Invited   | provisional + Invited    | SCY           |
 * | NAIA     | A + B             | **absent from source**   | SCY + SCM *   |
 *
 * NAIA relays are absent because the published file is explicitly
 * "...-wo-Relays". Absent is modelled as absent — never as zero, never invented.
 *
 * \* The NAIA 2026-27 sheet heads its second column "METERS" and never states
 * the pool length, so the generated file records that column as
 * `METRIC_UNSPECIFIED`. This loader reads it as SCM by a recorded decision,
 * {@link NAIA_2026_27_METERS_AS_SCM}, and stamps the decision on every record
 * it applies to (`courseDecision`). The values stay the 2026-27 sheet's.
 */

import type { NcaaDivision } from './types';
import rawSeason2025_2026 from '../../../data/cutlines/2025-2026.json';
import rawSeason2026_2027 from '../../../data/cutlines/2026-2027.json';

/* -------------------------------------------------------------------------- */
/* Vocabulary                                                                  */
/* -------------------------------------------------------------------------- */

/** Real published seasons. There are no projected or future seasons. */
export type CutlineSeason = '2025-2026' | '2026-2027';

/**
 * Racing course a loaded standard applies to.
 *
 * Every loaded record carries one of these three. A record whose source never
 * states its course is not loaded with a guess: it carries the course of a
 * recorded {@link CutlineCourseDecision}, or the loader throws.
 *
 * `METRIC_UNSPECIFIED` was a member until 2026-09-24. It survives only in the
 * generated files ({@link ExtractedCutlineCourse}); no loaded record, query or
 * tag uses it, so a query for it cannot come back silently empty.
 */
export type CutlineCourse = 'SCY' | 'SCM' | 'LCM';

/**
 * Course as `scripts/extract-cutlines.py` records it in `data/cutlines/*.json`.
 *
 * `METRIC_UNSPECIFIED` is what extraction can prove from a sheet that heads a
 * column "METERS" and states no pool length (the NAIA 2026-27 sheet). The
 * extractor stays faithful to the sheet; the course reading is a separate,
 * recorded decision applied at load time.
 */
export type ExtractedCutlineCourse = CutlineCourse | 'METRIC_UNSPECIFIED';

/**
 * A recorded reading of a course the values sheet does not state.
 *
 * This is a decision, not a fact the values sheet prints. It names both
 * sources: the sheet the **values** come from, and the archived document the
 * **course** reading rests on. No value is ever taken from the evidence
 * document. The decision covers only the exact bytes of the values sheet
 * (`valuesSha256`); a re-fetched sheet needs its own decision.
 */
export type CutlineCourseDecision = {
  /** Stable name of the decision. */
  id: string;
  division: NcaaDivision;
  season: CutlineSeason;
  /** Manifest id of the sheet the values come from, verbatim. */
  valuesSourceId: string;
  /** sha256 of that sheet. The decision applies to these bytes only. */
  valuesSha256: string;
  /** What the values sheet prints over the column, verbatim. */
  valuesSheetHeading: string;
  /** What extraction could prove from the values sheet alone. */
  extractedCourse: 'METRIC_UNSPECIFIED';
  /** The course the decision reads the column as. */
  course: CutlineCourse;
  /** The archived document the course reading rests on. No values come from it. */
  evidence: {
    /** Manifest id in `data/cutlines/sources/manifest.json`. */
    sourceId: string;
    season: string;
    url: string;
    sha256: string;
    /** What the evidence shows. */
    finding: string;
    /** What a reader should know about the evidence copy. */
    caveat: string;
  };
  decidedBy: 'user';
  /** ISO date of the decision. */
  decidedOn: string;
};

/**
 * User decision, 2026-09-24: read the NAIA 2026-27 "METERS" column as short
 * course metres (SCM).
 *
 * - Values: `data/cutlines/sources/2026-27-SD-Qualifying-Standards-wo-Relays.pdf`
 *   (manifest id `naia-2026-27`). That sheet heads the column "METERS" and
 *   never says SCM or LCM.
 * - Course: `data/cutlines/sources/2020-21-NAIA-SD-Qualifying-Standards.pdf`
 *   (manifest id `naia-2020-21-course-evidence`). The official NAIA 2020-21
 *   sheet heads the same column "SCM". Only that heading is used.
 *
 * `tests/naiaMeterCourseAsScm.test.ts` re-reads both headings from the PDFs
 * and pins both hashes against the manifest.
 */
export const NAIA_2026_27_METERS_AS_SCM: Readonly<CutlineCourseDecision> = Object.freeze({
  id: 'naia-2026-27-meters-as-scm',
  division: 'NAIA',
  season: '2026-2027',
  valuesSourceId: 'naia-2026-27',
  valuesSha256: '395be842a2fde60a25348ed9d534cbdf65024fb831626ccfa908ca00c130c166',
  valuesSheetHeading: 'METERS',
  extractedCourse: 'METRIC_UNSPECIFIED',
  course: 'SCM',
  evidence: Object.freeze({
    sourceId: 'naia-2020-21-course-evidence',
    season: '2020-2021',
    url: 'https://www.gomotionapp.com/cantbt/UserFiles/Image/QuickUpload/naia-qualifying-times_088712.pdf',
    sha256: 'c672d8bcbbdcf2b69b94dc6fbfe701cf6a724fb738cdd14de0fda4a18022b132',
    finding: 'The official NAIA 2020-21 qualifying sheet heads its metric column "SCM".',
    caveat:
      'Hosted by a club site (gomotionapp), not naia.org. The naia.org coaches manual URL returned 404 on 2026-09-24.',
  }),
  decidedBy: 'user',
  decidedOn: '2026-09-24',
} satisfies CutlineCourseDecision);

export type CutlineGender = 'Men' | 'Women';

export type DivingBoard = '1M' | '3M' | 'PLATFORM';

/**
 * Honest name of a single published tier. `Standard` is D1's one-column
 * individual standard, which is neither an "A" nor a "B" cut.
 */
export type CutlineTier = 'Standard' | 'A' | 'B' | 'Invited' | 'Qualifying' | 'Provisional';

/** Where a record came from. Present on every record, no exceptions. */
export type CutlineSourceRef = {
  sourceId: string;
  url: string;
  /** sha256 of the archived PDF, matching data/cutlines/sources/manifest.json. */
  sha256: string;
  /** 1-based page of the PDF the row was read from. */
  page: number;
};

type CutlineCommon = {
  division: NcaaDivision;
  season: CutlineSeason;
  gender: CutlineGender;
  /** Canonical long-form event name, e.g. "100 Backstroke", "200 Medley Relay". */
  event: string;
  course: CutlineCourse;
  /** Where the values came from. Always the values sheet, never the course evidence. */
  source: CutlineSourceRef;
  /**
   * Present only when the values sheet does not state this record's course and
   * `course` comes from a recorded decision instead. Absent means `course` is
   * the one the extractor read off the values sheet itself.
   */
  courseDecision?: Readonly<CutlineCourseDecision>;
};

/* -------------------------------------------------------------------------- */
/* The discriminated union                                                     */
/* -------------------------------------------------------------------------- */

/** D1: one `STANDARD` column, no A/B split at the individual level. */
export type IndividualSingleCutline = CutlineCommon & {
  kind: 'individual';
  scale: 'single';
  standard: string;
};

/** D2 and NAIA: A standard + B standard. */
export type IndividualABCutline = CutlineCommon & {
  kind: 'individual';
  scale: 'ab';
  aStandard: string;
  bStandard: string;
};

/** D3: A + B + `Invited`, where Invited is the real selection cutline. */
export type IndividualABInvitedCutline = CutlineCommon & {
  kind: 'individual';
  scale: 'abInvited';
  aStandard: string;
  bStandard: string;
  invitedStandard: string;
};

export type IndividualCutline =
  | IndividualSingleCutline
  | IndividualABCutline
  | IndividualABInvitedCutline;

/** D1: both a QUALIFYING and a PROVISIONAL relay standard. */
export type RelayQualifyingProvisionalCutline = CutlineCommon & {
  kind: 'relay';
  scale: 'qualifyingProvisional';
  qualifying: string;
  provisional: string;
};

/** D2: the QUALIFYING column is printed `N/A`; only the provisional is real. */
export type RelayProvisionalOnlyCutline = CutlineCommon & {
  kind: 'relay';
  scale: 'provisionalOnly';
  provisional: string;
};

/** D3: the A column is printed `NA`; a provisional and an Invited cut are real. */
export type RelayProvisionalInvitedCutline = CutlineCommon & {
  kind: 'relay';
  scale: 'provisionalInvited';
  provisional: string;
  invited: string;
};

export type RelayCutline =
  | RelayQualifyingProvisionalCutline
  | RelayProvisionalOnlyCutline
  | RelayProvisionalInvitedCutline;

/**
 * One board × one dive-list size. A board that publishes both a 6-dive and an
 * 11-dive total is two records, not one record with a guessed default.
 */
export type DivingCutline = CutlineCommon & {
  kind: 'diving';
  board: DivingBoard;
  /** Size of the dive list this point total applies to (5, 6 or 11). */
  diveCount: number;
  points: number;
  /** Only present where the source prints a numeric minimum. */
  minimumDegreeOfDifficulty?: number;
  /** Verbatim footnote from the source, where one applies. */
  note?: string;
};

/** Anything with a clock time: an individual event or a relay. */
export type SwimCutline = IndividualCutline | RelayCutline;

export type CutlineEntry = SwimCutline | DivingCutline;

/* -------------------------------------------------------------------------- */
/* Generated-file shape                                                        */
/* -------------------------------------------------------------------------- */

export type CutlineSourceSummary = {
  id: string;
  division: NcaaDivision;
  url: string;
  sha256: string;
  retrievedAt: string | null;
  pageCount: number | null;
};

/**
 * A season file as loaded: the generated file with every recorded course
 * decision applied to its records. See {@link cutlineDataFiles}.
 */
export type CutlineDataFile = {
  version: string;
  season: CutlineSeason;
  generatedAt: string;
  generator: string;
  divisions: NcaaDivision[];
  sources: CutlineSourceSummary[];
  cutlines: CutlineEntry[];
};

type WithExtractedCourse<E> = E extends CutlineEntry
  ? Omit<E, 'course' | 'courseDecision'> & { course: ExtractedCutlineCourse }
  : never;

/** One record exactly as `data/cutlines/<season>.json` holds it. */
export type GeneratedCutlineEntry = WithExtractedCourse<CutlineEntry>;

type GeneratedCutlineDataFile = Omit<CutlineDataFile, 'cutlines'> & {
  cutlines: GeneratedCutlineEntry[];
};

/* -------------------------------------------------------------------------- */
/* Course decisions                                                            */
/* -------------------------------------------------------------------------- */

const COURSE_DECISIONS: readonly Readonly<CutlineCourseDecision>[] = Object.freeze([
  NAIA_2026_27_METERS_AS_SCM,
]);

/** Every recorded course decision the loader applies. */
export function cutlineCourseDecisions(): readonly Readonly<CutlineCourseDecision>[] {
  return COURSE_DECISIONS;
}

/**
 * The loaded form of one generated record.
 *
 * A record whose course the extractor could read passes through unchanged. A
 * `METRIC_UNSPECIFIED` record takes the course of the one decision that names
 * its values source, division and season **and** its exact source bytes, and
 * carries that decision as `courseDecision`.
 *
 * Throws when no decision matches. A record with an unstated course is never
 * loaded under a guess, and never dropped in silence: a new or re-fetched
 * sheet needs its own recorded decision before the tables load.
 */
export function resolveCutlineCourse(
  entry: GeneratedCutlineEntry,
  decisions: readonly Readonly<CutlineCourseDecision>[] = COURSE_DECISIONS
): CutlineEntry {
  if (entry.course !== 'METRIC_UNSPECIFIED') return entry as CutlineEntry;
  const where = `${entry.division} ${entry.season} ${entry.gender} ${entry.event} (source ${entry.source.sourceId})`;
  const decision = decisions.find(d => d.valuesSourceId === entry.source.sourceId);
  if (!decision) {
    throw new Error(
      `Cutline ${where} does not state its course, and no recorded course decision names source ${entry.source.sourceId}.`
    );
  }
  if (decision.valuesSha256 !== entry.source.sha256) {
    throw new Error(
      `Cutline ${where} cites sha256 ${entry.source.sha256}; course decision ${decision.id} covers only ${decision.valuesSha256}. Record a decision for the new sheet.`
    );
  }
  if (decision.division !== entry.division || decision.season !== entry.season) {
    throw new Error(
      `Cutline ${where} does not match course decision ${decision.id} (${decision.division} ${decision.season}).`
    );
  }
  return { ...entry, course: decision.course, courseDecision: decision } as CutlineEntry;
}

function loadDataFile(file: GeneratedCutlineDataFile): CutlineDataFile {
  return { ...file, cutlines: file.cutlines.map(entry => resolveCutlineCourse(entry)) };
}

const DATA_FILES: readonly CutlineDataFile[] = [
  rawSeason2025_2026 as unknown as GeneratedCutlineDataFile,
  rawSeason2026_2027 as unknown as GeneratedCutlineDataFile,
].map(loadDataFile);

const ALL_ENTRIES: readonly CutlineEntry[] = DATA_FILES.flatMap(file => file.cutlines);

/* -------------------------------------------------------------------------- */
/* Type guards                                                                 */
/* -------------------------------------------------------------------------- */

export function isIndividualCutline(entry: CutlineEntry): entry is IndividualCutline {
  return entry.kind === 'individual';
}

export function isRelayCutline(entry: CutlineEntry): entry is RelayCutline {
  return entry.kind === 'relay';
}

export function isDivingCutline(entry: CutlineEntry): entry is DivingCutline {
  return entry.kind === 'diving';
}

export function isSwimCutline(entry: CutlineEntry): entry is SwimCutline {
  return entry.kind === 'individual' || entry.kind === 'relay';
}

/* -------------------------------------------------------------------------- */
/* Loader API                                                                  */
/* -------------------------------------------------------------------------- */

/** Every published record across every season and division. */
export function publishedCutlines(): readonly CutlineEntry[] {
  return ALL_ENTRIES;
}

/**
 * The generated files with their provenance blocks, as loaded: every recorded
 * course decision is applied, so no record carries `METRIC_UNSPECIFIED`.
 */
export function cutlineDataFiles(): readonly CutlineDataFile[] {
  return DATA_FILES;
}

/** Seasons we hold data for, newest first. */
export function cutlineSeasons(): CutlineSeason[] {
  return [...new Set(DATA_FILES.map(f => f.season))].sort().reverse() as CutlineSeason[];
}

/** Divisions that have any published table at all. */
export function divisionsWithCutlineData(): NcaaDivision[] {
  return [...new Set(ALL_ENTRIES.map(e => e.division))].sort() as NcaaDivision[];
}

/** Seasons published for one division, newest first. Empty means no data. */
export function publishedSeasonsForDivision(division: NcaaDivision): CutlineSeason[] {
  const seasons = new Set<CutlineSeason>();
  for (const entry of ALL_ENTRIES) {
    if (entry.division === division) seasons.add(entry.season);
  }
  return [...seasons].sort().reverse();
}

/**
 * Newest published season for a division, or `null` when we hold none.
 * `null` is the honest answer and must not be collapsed to a default season.
 */
export function latestSeasonForDivision(division: NcaaDivision): CutlineSeason | null {
  return publishedSeasonsForDivision(division)[0] ?? null;
}

/** True when a table exists for this division (and season, when given). */
export function hasCutlineTable(division: NcaaDivision, season?: CutlineSeason): boolean {
  return ALL_ENTRIES.some(
    e => e.division === division && (season === undefined || e.season === season)
  );
}

/** Provenance for every archived source behind the loaded tables. */
export function cutlineSources(): CutlineSourceSummary[] {
  return DATA_FILES.flatMap(f => f.sources);
}

export type CutlineQuery = {
  division?: NcaaDivision;
  season?: CutlineSeason;
  gender?: CutlineGender;
  course?: CutlineCourse;
  kind?: CutlineEntry['kind'];
  /** Matched case-insensitively against the canonical event name. */
  event?: string;
};

/** Filter the published set. Returns `[]` when nothing matches — check `hasCutlineTable` to tell absent from unmatched. */
export function findCutlines(query: CutlineQuery): CutlineEntry[] {
  const wantedEvent = query.event?.trim().toUpperCase();
  return ALL_ENTRIES.filter(entry => {
    if (query.division && entry.division !== query.division) return false;
    if (query.season && entry.season !== query.season) return false;
    if (query.gender && entry.gender !== query.gender) return false;
    if (query.course && entry.course !== query.course) return false;
    if (query.kind && entry.kind !== query.kind) return false;
    if (wantedEvent && entry.event.toUpperCase() !== wantedEvent) return false;
    return true;
  });
}

/** Published diving point totals for a division/gender, newest season by default. */
export function getDivingCutlines(
  gender: CutlineGender,
  division: NcaaDivision,
  season?: CutlineSeason
): DivingCutline[] {
  const resolved = season ?? latestSeasonForDivision(division);
  if (!resolved) return [];
  return findCutlines({ division, gender, season: resolved, kind: 'diving' }) as DivingCutline[];
}

/* -------------------------------------------------------------------------- */
/* Tier extraction                                                             */
/* -------------------------------------------------------------------------- */

/** One published tier of one record: its honest label and its verbatim time. */
export type CutlineTierTime = { tier: CutlineTier; time: string };

/**
 * The tiers a swim record publishes, strictest (fastest) first.
 * A tier a division does not publish simply does not appear.
 */
export function cutlineTierTimes(entry: SwimCutline): CutlineTierTime[] {
  if (entry.kind === 'individual') {
    switch (entry.scale) {
      case 'single':
        return [{ tier: 'Standard', time: entry.standard }];
      case 'ab':
        return [
          { tier: 'A', time: entry.aStandard },
          { tier: 'B', time: entry.bStandard },
        ];
      case 'abInvited':
        return [
          { tier: 'A', time: entry.aStandard },
          { tier: 'Invited', time: entry.invitedStandard },
          { tier: 'B', time: entry.bStandard },
        ];
    }
  }
  switch (entry.scale) {
    case 'qualifyingProvisional':
      return [
        { tier: 'Qualifying', time: entry.qualifying },
        { tier: 'Provisional', time: entry.provisional },
      ];
    case 'provisionalOnly':
      return [{ tier: 'Provisional', time: entry.provisional }];
    case 'provisionalInvited':
      return [
        { tier: 'Invited', time: entry.invited },
        { tier: 'Provisional', time: entry.provisional },
      ];
  }
}

/* -------------------------------------------------------------------------- */
/* Legacy flat view                                                            */
/* -------------------------------------------------------------------------- */

/**
 * Flattened A/B row, kept so existing callers keep compiling.
 *
 * @deprecated Prefer {@link CutlineEntry} and {@link cutlineTierTimes}. This
 * shape cannot express D1's single standard, D3's `Invited` tier, or diving, and
 * its `time_25_26` field name is a leftover that no longer describes its
 * contents. `tier` carries the honest label.
 */
export type CutlineRecord = {
  division: NcaaDivision;
  gender: string;
  event: string;
  /** Legacy two-tier slot. See `tier` for what the source actually calls it. */
  standard: 'A' | 'B';
  /**
   * Published standard, verbatim.
   * @deprecated Misleading name — this is not necessarily a 2025-26 time. Use `time`.
   */
  time_25_26: string;
  /** Published standard, verbatim. */
  time: string;
  /** What the source actually calls this tier. */
  tier: CutlineTier;
  season: CutlineSeason;
  course: CutlineCourse;
  source: CutlineSourceRef;
};

function legacyRows(entry: SwimCutline): CutlineRecord[] {
  const base = {
    division: entry.division,
    gender: entry.gender as string,
    event: entry.event,
    season: entry.season,
    course: entry.course,
    source: entry.source,
  };
  // The legacy shape has exactly two slots. `Standard` and `Qualifying` occupy
  // the strict slot; `B`, `Provisional` the permissive one. `Invited` has no
  // legacy slot and is reachable only through the typed API.
  const slotFor = (tier: CutlineTier): 'A' | 'B' | null => {
    switch (tier) {
      case 'Standard':
      case 'Qualifying':
      case 'A':
        return 'A';
      case 'B':
      case 'Provisional':
        return 'B';
      case 'Invited':
        return null;
    }
  };
  const rows: CutlineRecord[] = [];
  for (const { tier, time } of cutlineTierTimes(entry)) {
    const slot = slotFor(tier);
    if (!slot) continue;
    rows.push({ ...base, standard: slot, tier, time, time_25_26: time });
  }
  return rows;
}

const LEGACY_ROWS: CutlineRecord[] = ALL_ENTRIES.filter(isSwimCutline).flatMap(legacyRows);

/**
 * Legacy flat view over **every** published division and season.
 *
 * @deprecated Use {@link publishedCutlines}. Note this is no longer D1-only:
 * the previous D1-only `cutlines` export was the direct cause of D2 lookups
 * silently returning nothing.
 */
export const cutlines: CutlineRecord[] = LEGACY_ROWS;

/** Legacy flat view over every published division and season. */
export function allCutlines(): CutlineRecord[] {
  return LEGACY_ROWS;
}
