// GENERATED by extensions/swimcloud-companion/build.mjs — do not edit.
// Edit the matching file under extensions/swimcloud-companion/src/ and re-run that script.

"use strict";
(() => {
  // packages/swimcloud/src/entities.ts
  function captureIdForSubject(subject) {
    if (subject.kind === "meet") {
      return `meet-${subject.meetId}`;
    }
    return subject.season === void 0 ? `team-${subject.teamId}` : `team-${subject.teamId}-${subject.season}`;
  }

  // extensions/swimcloud-companion/src/backgroundRoundTrip.ts
  function errorText(error) {
    if (error instanceof Error && error.message.length > 0) return error.message;
    if (typeof error === "string" && error.length > 0) return error;
    try {
      return String(error);
    } catch {
      return "unknown error";
    }
  }

  // extensions/swimcloud-companion/src/background.ts
  var DEFAULT_PORT = 3e3;
  var LOCAL_REQUEST_TIMEOUT_MS = 8e3;
  var CAPTURE_TOKEN_HEADER = "X-Omniswim-Capture-Token";
  var OPTIONS_KEYS = {
    token: "omniswimPairingToken",
    port: "omniswimAppPort"
  };
  async function loadOptions() {
    const stored = await chrome.storage.local.get([OPTIONS_KEYS.token, OPTIONS_KEYS.port]);
    const token = stored[OPTIONS_KEYS.token];
    const port = Number(stored[OPTIONS_KEYS.port]);
    return {
      token: typeof token === "string" ? token : "",
      port: Number.isFinite(port) && port > 0 ? port : DEFAULT_PORT
    };
  }
  function captureBase(port) {
    return `http://127.0.0.1:${port}/api/swimcloud/captures`;
  }
  async function requestJson(url, init) {
    const controller = new AbortController();
    const deadline = setTimeout(() => controller.abort(), LOCAL_REQUEST_TIMEOUT_MS);
    try {
      const response = await fetch(url, { ...init, signal: controller.signal });
      let json;
      try {
        json = await response.json();
      } catch {
        json = void 0;
      }
      return { ok: response.ok, status: response.status, json };
    } finally {
      clearTimeout(deadline);
    }
  }
  async function postJson(url, token, body) {
    return requestJson(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        [CAPTURE_TOKEN_HEADER]: token
      },
      body: JSON.stringify(body)
    });
  }
  async function getJson(url, token) {
    return requestJson(url, { headers: { [CAPTURE_TOKEN_HEADER]: token } });
  }
  async function registerOrUpdateCapture(subject, extra) {
    try {
      const { token, port } = await loadOptions();
      if (!token) return void 0;
      const result = await postJson(captureBase(port), token, { subject, ...extra });
      const json = result.json;
      if (result.ok && typeof json === "object" && json !== null && "captureId" in json) {
        const captureId = json.captureId;
        if (typeof captureId === "string") return captureId;
      }
    } catch {
    }
    return void 0;
  }
  async function readCapture(subject) {
    let captureId = "";
    try {
      captureId = captureIdForSubject(subject);
      const { token, port } = await loadOptions();
      if (!token) return { captureId, available: false, found: false };
      const result = await getJson(`${captureBase(port)}/${captureId}?withEventRefs=1`, token);
      if (result.status === 404) return { captureId, available: true, found: false };
      if (!result.ok || result.json === void 0) return { captureId, available: false, found: false };
      return { captureId, available: true, found: true, capture: result.json };
    } catch {
      return { captureId, available: false, found: false };
    }
  }
  async function relayPage(message) {
    let captureId = "";
    try {
      const { token, port } = await loadOptions();
      captureId = captureIdForSubject(message.subject);
      const payload = {
        omniswimSwimCloudCapture: 2,
        subject: message.subject,
        sourceUrl: message.sourceUrl,
        retrievedAt: message.retrievedAt,
        track: "browser-extension",
        ...message.httpStatus === void 0 ? {} : { httpStatus: message.httpStatus },
        html: message.html
      };
      if (token) {
        try {
          const result = await postJson(`${captureBase(port)}/${captureId}/pages`, token, payload);
          if (result.ok) {
            return { relayed: true, via: "http" };
          }
        } catch {
        }
      }
    } catch (error) {
      return { relayed: false, via: "downloads", error: errorText(error) };
    }
    return downloadFallback(captureId, message);
  }
  async function downloadFallback(captureId, message) {
    try {
      const entry = {
        omniswimSwimCloudCapture: 2,
        subject: message.subject,
        sourceUrl: message.sourceUrl,
        retrievedAt: message.retrievedAt,
        track: "browser-extension",
        httpStatus: message.httpStatus,
        html: message.html
      };
      await appendFallbackPage(captureId, entry);
      return { relayed: true, via: "downloads" };
    } catch (error) {
      return { relayed: false, via: "downloads", error: errorText(error) };
    }
  }
  function fallbackIndexKey(captureId) {
    return `omniswimFallbackIndex:${captureId}`;
  }
  function fallbackPageKey(captureId, n) {
    return `omniswimFallbackPage:${captureId}:${n}`;
  }
  async function appendFallbackPage(captureId, entry) {
    const indexKey = fallbackIndexKey(captureId);
    const stored = await chrome.storage.local.get([indexKey]);
    const existingKeys = Array.isArray(stored[indexKey]) ? stored[indexKey] : [];
    const nextKey = fallbackPageKey(captureId, existingKeys.length);
    await chrome.storage.local.set({ [nextKey]: entry });
    await chrome.storage.local.set({ [indexKey]: [...existingKeys, nextKey] });
  }
  async function flushDownloads(captureId) {
    const indexKey = fallbackIndexKey(captureId);
    try {
      const stored = await chrome.storage.local.get([indexKey]);
      const keys = Array.isArray(stored[indexKey]) ? stored[indexKey] : [];
      if (keys.length === 0) {
        return { flushed: true, pageCount: 0 };
      }
      const pagesById = await chrome.storage.local.get(keys);
      const pages = keys.map((key) => pagesById[key]).filter((page) => page !== void 0);
      const combined = JSON.stringify(
        { omniswimSwimCloudCaptureBundle: 1, captureId, pageCount: pages.length, pages },
        null,
        2
      );
      const dataUrl = `data:application/json;base64,${btoa(unescape(encodeURIComponent(combined)))}`;
      const filename = `omniswim-swimcloud-captures/${captureId}/combined-capture.json`;
      await chrome.downloads.download({ url: dataUrl, filename, conflictAction: "uniquify", saveAs: false });
      await chrome.storage.local.remove([...keys, indexKey]);
      return { flushed: true, pageCount: pages.length, filename };
    } catch (error) {
      return { flushed: false, pageCount: 0, error: errorText(error) };
    }
  }
  function messageType(message) {
    if (typeof message !== "object" || message === null) return void 0;
    const type = message.type;
    return typeof type === "string" ? type : void 0;
  }
  var HANDLERS = {
    "omniswim-swimcloud-open-capture": async (message) => {
      const open = message;
      const captureId = await registerOrUpdateCapture(open.subject, {
        completeness: "in-progress",
        plannedPageCount: open.plannedPageCount,
        track: "browser-extension",
        ...open.teamDiscovery === void 0 ? {} : { teamDiscovery: open.teamDiscovery }
      });
      return { captureId };
    },
    "omniswim-swimcloud-mark-capture": async (message) => {
      const mark = message;
      return { captureId: await registerOrUpdateCapture(mark.subject, { completeness: mark.completeness }) };
    },
    "omniswim-swimcloud-read-capture": async (message) => readCapture(message.subject),
    "omniswim-swimcloud-relay-page": async (message) => relayPage(message),
    "omniswim-swimcloud-flush-downloads": async (message) => {
      const flush = message;
      return flushDownloads(captureIdForSubject(flush.subject));
    }
  };
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    const type = messageType(message);
    if (type === void 0) return void 0;
    const handler = HANDLERS[type];
    if (handler === void 0) return void 0;
    let settled = false;
    const respond = (value) => {
      if (settled) return;
      settled = true;
      try {
        sendResponse(value);
      } catch {
      }
    };
    void (async () => {
      try {
        respond(await handler(message));
      } catch (error) {
        respond({ error: errorText(error) });
      }
    })();
    return true;
  });
})();
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * SwimCloud source entities.
 *
 * Shape adapted from `plans/2026-09-06/02-data-model-and-scoring.md` §2, which in
 * turn adapts the W3C OpenTrack Community Group's Open Athletics Data Model
 * (Competition → UnitCompetition → Competitor → Performance → Result).
 *
 * Three rules from `CLAUDE.md` § "Data provenance" govern every type in this
 * file, and they are the reason several fields look more awkward than they
 * strictly need to:
 *
 * 1. **Unknown ≠ a default.** A course we could not determine is `'unknown'`,
 *    never silently `'SCY'`; a ruleset we could not determine is `'unknown'`,
 *    never silently `'NCAA'`. This mirrors the existing "unknown division ≠ D1"
 *    rule in `packages/core/src/data/teamDivisions.ts`.
 * 2. **Absent ≠ zero.** A competition value we do not hold is an omitted
 *    optional field, never `0` and never an interpolated estimate.
 * 3. **Unverified is labelled.** Nothing in this file has been checked against
 *    real SwimCloud markup — see {@link SwimCloudParseConfidence} in
 *    `./parser.ts`. Fields whose *existence* on a SwimCloud page is unverified
 *    carry an explicit "unverified" doc-comment; treat their absence as the
 *    expected case, not as a parse bug.
 *
 * These types describe **what a SwimCloud page says**. They deliberately do not
 * import from `@omniswim/core`: the domain layer must not learn where an
 * Entry/Result came from (`plans/2026-09-06/03-architecture.md` §1). Mapping
 * these into the core roster/scoring model is a separate, later step.
 */
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Bounded round trips to the background service worker.
 *
 * ## Why this module exists
 *
 * `chrome.runtime.sendMessage(message, callback)` has exactly two outcomes the
 * caller can observe: the callback runs with a response, or the callback runs
 * with `chrome.runtime.lastError` set. It has **no third outcome for "the
 * worker never answered"**. If the background listener returns `true` — the
 * Manifest V3 promise that a response is coming — and then never calls
 * `sendResponse`, the callback is simply never invoked. A content script that
 * `await`s that message waits forever: no rejection, no timeout, no console
 * error. The crawl panel freezes on whatever line it last rendered and a coach
 * watching it has no way to tell a stalled crawl from a slow one.
 *
 * That is not hypothetical. Every handler in `./background.ts` used to be
 * `handler(message).then(sendResponse)` with no `.catch`, over functions that
 * did work (`await loadOptions()`, `captureIdForSubject(...)`, `btoa(...)`)
 * *outside* their own `try` blocks. Any throw on those lines rejected the
 * promise, skipped the `.then`, and left the message channel open and silent
 * for the rest of the tab's life.
 *
 * So: no `chrome.runtime.sendMessage` on the crawl's critical path is awaited
 * unbounded. Every one goes through {@link sendWithTimeout}, which always
 * settles — `ok`, `timeout` or `error` — and the caller decides what a failure
 * degrades to. A visibly degraded crawl is recoverable. A silent one is not.
 *
 * Pure by construction: the timers are injected, `send` is any thunk returning
 * a promise, and nothing here touches `chrome.*`, the DOM, or the network. That
 * is what makes "a round trip that never answers becomes a timeout, not a
 * hang" a unit test (`tests/swimCloudExtensionBackgroundRoundTrip.test.ts`)
 * rather than something only a live meet can prove.
 */
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Omniswim SwimCloud Companion — background service worker.
 *
 * Per `plans/2026-09-08/03-extension-crawler.md`'s "Where the crawl loop
 * actually runs": the content script (`content.js` for Track A, `crawler.js`
 * for Track A′) owns the crawl loop and fetches SwimCloud pages itself,
 * same-origin, no extra permission needed. This worker's job is deliberately
 * narrow — the things that DO need extension-level privilege:
 *
 *   1. Relay each fetched page on to the local app's capture-store HTTP route
 *      (`POST http://127.0.0.1:{PORT}/api/swimcloud/captures/{id}/pages`),
 *      which is cross-origin from the SwimCloud page and needs the
 *      `host_permissions` entry this manifest grants for `127.0.0.1`.
 *   2. Open and update the capture record on that same host.
 *   3. Read an existing capture back, so a restarted crawl can skip pages the
 *      store already holds instead of re-fetching them from SwimCloud.
 *   4. Own the `chrome.downloads` fallback for when a POST fails (the app
 *      isn't running, wrong port, …) so a page is never silently lost.
 *
 * This file never runs the crawl itself, never decides pacing, and never
 * parses page content — see that design doc section for why the split is
 * deliberate.
 *
 * ## Why this is TypeScript, bundled, and no longer hand-written JS
 *
 * It used to carry its own copy of the capture-id rule (`captureIdGuess`),
 * duplicating `captureIdForSubject`. The two agreed only by construction: the
 * team-with-season branch is not reachable yet, so nothing exercised it, and a
 * change to the real rule would have made every page POST target a capture id
 * nobody had opened — a 404, a silent fall-through to `chrome.downloads`, and
 * no server-store integration at all, with no test to catch it. The rule now
 * lives once, in `packages/swimcloud/src/entities.ts` (Node-free by design, so
 * both this worker and the app's Node process can import it), and `build.mjs`
 * bundles this file into `../background.js` the same way it bundles the crawl
 * loop into `../crawler.js`.
 */
