/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * The extension's build inputs, in one place so two callers cannot drift.
 *
 * `./build.mjs` is the CLI that writes the bundles.
 * `tests/swimCloudExtensionBuildFreshness.test.ts` rebuilds with these exact
 * options in memory and fails if the committed artifacts differ.
 *
 * That second caller is the reason this file exists. Before it, the build was
 * manual: not in any npm script, not in CI, and unverified by any test. Editing
 * a file under `src/` and forgetting to re-run the build left `crawler.js`
 * silently serving the previous logic to a loaded extension, with nothing
 * anywhere reporting a mismatch. Keeping the options here — rather than copied
 * into the test — means the guard checks the real build, not a lookalike.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const extensionRoot = path.dirname(fileURLToPath(import.meta.url));

/** Both outputs are generated. Say so at the top of the file people will open first. */
export const GENERATED_BANNER =
  '// GENERATED by extensions/swimcloud-companion/build.mjs — do not edit.\n' +
  '// Edit the matching file under extensions/swimcloud-companion/src/ and re-run that script.\n';

/** Entry point -> committed artifact. */
export const entries = [
  { in: path.join(extensionRoot, 'src', 'crawler-content.ts'), out: path.join(extensionRoot, 'crawler.js') },
  { in: path.join(extensionRoot, 'src', 'background.ts'), out: path.join(extensionRoot, 'background.js') },
];

/**
 * Everything except `entryPoints`/`outfile`, which differ per entry, and
 * `write`, which differs per caller — the CLI writes, the test does not.
 */
export const sharedBuildOptions = {
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['chrome110'],
  banner: { js: GENERATED_BANNER },
};
