/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Naming a workspace after the meet it holds.
 *
 * A workspace is created before it has any content, so it gets a placeholder
 * (`Blank Workspace 1`). Loading a meet PDF into it gives it an identity, but the
 * placeholder stuck — the live workspace holding the 2026 NSISC Championships was
 * still called "Blank Workspace 1", while the one named for a roster held no meet
 * at all. Anyone opening the app cold read it exactly backwards.
 *
 * The name is derived from the file the operator chose, never invented: if the
 * filename yields nothing usable, the placeholder is kept rather than replaced
 * with a guess.
 *
 * Test: npx tsx scripts/test_workspace_naming.mjs
 */

/**
 * Placeholder names the app itself generates. Only these are replaced — a name
 * the user typed is theirs and is never overwritten.
 *
 * `Blank Workspace N` comes from `SuiteWorkspaceProvider.handleCreateWorkspace`;
 * `New Workspace` is the server-side fallback in `POST /api/workspaces`.
 */
const AUTO_NAME_PATTERNS: RegExp[] = [
  /^blank workspace(\s+\d+)?$/i,
  /^new workspace(\s+\d+)?$/i,
  /^workspace(\s+\d+)?$/i,
  /^untitled(\s+workspace)?(\s+\d+)?$/i,
];

/** True when this name was generated by the app rather than chosen by the user. */
export function isAutoGeneratedWorkspaceName(name: string | undefined | null): boolean {
  const trimmed = String(name ?? '').trim();
  if (!trimmed) return true;
  return AUTO_NAME_PATTERNS.some(re => re.test(trimmed));
}

/**
 * Words a results PDF carries that describe the *document*, not the *meet*.
 * Dropped from the tail only — a meet legitimately called "Finals Invitational"
 * keeps its words because they are not trailing.
 */
const TRAILING_NOISE = new Set([
  'results',
  'result',
  'final',
  'finals',
  'complete',
  'official',
  'meet',
  'psych',
  'sheet',
  'heat',
  'sheets',
  'copy',
  'updated',
  'revised',
  'v2',
  'v3',
]);

/**
 * A readable meet name from a PDF filename, or null when nothing usable remains.
 *
 * `2026_NSISC_Championships_Final_Results.pdf` -> `2026 NSISC Championships`
 *
 * Casing is left alone: acronyms (NSISC, NCAA) outnumber prose here, and
 * title-casing would turn them into `Nsisc`.
 */
export function meetNameFromPdfFilename(pdfFilename: string | undefined | null): string | null {
  const raw = String(pdfFilename ?? '').trim();
  if (!raw) return null;

  // Strip any directory prefix a browser may include, then the extension.
  const base = raw.split(/[\\/]/).pop() ?? raw;
  const withoutExt = base.replace(/\.[a-z0-9]{1,5}$/i, '');

  const words = withoutExt
    .replace(/[_\-+]+/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim()
    .split(' ')
    .filter(Boolean);
  if (!words.length) return null;

  // Drop document-describing words from the tail only.
  let end = words.length;
  while (end > 0 && TRAILING_NOISE.has(words[end - 1].toLowerCase())) end -= 1;
  const kept = words.slice(0, end);
  if (!kept.length) return null;

  const name = kept.join(' ').trim();
  // A bare number or a single stray character is not a name worth adopting.
  if (name.length < 3) return null;
  if (/^\d+$/.test(name)) return null;

  return name.length > 60 ? `${name.slice(0, 59).trimEnd()}…` : name;
}

/**
 * The name a workspace should take when a meet is loaded into it, or null to
 * leave the current name alone.
 *
 * Returns null when the current name is user-chosen, when the filename yields
 * nothing usable, or when the derived name matches what is already there.
 */
export function workspaceNameForLoadedMeet(
  currentName: string | undefined | null,
  pdfFilename: string | undefined | null,
  conference?: string | null
): string | null {
  if (!isAutoGeneratedWorkspaceName(currentName)) return null;

  const fromFile = meetNameFromPdfFilename(pdfFilename);
  if (!fromFile) return null;

  // Add the detected conference only when the filename does not already say it,
  // so "2026 NSISC Championships" does not become "2026 NSISC Championships (NSISC)".
  const conf = String(conference ?? '').trim();
  const alreadyMentioned =
    conf.length > 0 && new RegExp(`\\b${conf.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i').test(fromFile);
  const name = conf && !alreadyMentioned ? `${fromFile} (${conf})` : fromFile;

  if (name.trim() === String(currentName ?? '').trim()) return null;
  return name;
}
