/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Re-extract one meet workspace in `data/meets.json` from its source PDF.
 *
 * A workspace's results are parser output. When the parser is fixed, the
 * committed results are stale until the meet is parsed again — which is how
 * `test_nsisc_team_totals.mjs` came to carry a documented XFAIL. Hand-patching
 * the JSON is not an option: `CLAUDE.md` bans typing competition values into a
 * fixture, because a reviewer cannot check the transcription against anything.
 * So the fixture is regenerated by the same pipeline the app runs
 * (`backend/parse_meet.py`) and mapped by the same code the server uses
 * (`mapAthleteRows` from `apps/shell/lib/routes/parsingPipeline.ts`).
 *
 * Writes exactly five fields:
 *   menResults, womenResults, sourceMenResults, sourceWomenResults,
 *   officialTeamScores
 *
 * Everything else in the workspace — id, name, createdAt, scoringSettings,
 * conference, meetEntryPlans, activeEntryIds, recruits, athleteHistory,
 * athleteAliases, scorerRosterOverrides, relayLegOverrides, deletedSwimmers,
 * loadedMeet, historySources — is carried across untouched, and the script
 * verifies that afterwards rather than trusting itself.
 *
 * ## Row ids are preserved
 *
 * A fresh parse would mint a fresh uuid for all ~930 rows, which would orphan
 * anything that stores a result-row id — `meetEntryPlans[].replacesResultId`
 * (see `editCreditedSwim` in `packages/core/src/lib/swimEditor.ts`) is the one
 * that matters, and an orphaned overlay fails silently: it stops finding the row
 * it replaces and the edit disappears with no error. So a row that already
 * exists keeps its id, matched on its content rather than its position, and only
 * genuinely new rows get a new uuid. The script refuses to run if the workspace
 * holds an id reference it would break.
 *
 * The SQLite store (`omniswim.db`, gitignored) is not touched.
 *
 * ## Which file it writes
 *
 * `<data dir>/meets.json`. The data dir is the repo's `data/` folder unless
 * `OMNI_DATA_DIR` is set (same resolution as apps/shell/server.ts). The resolved
 * path is printed first, so the real store is never targeted silently. This
 * script does not start a server; the only subprocess is `backend/parse_meet.py`.
 * Before it writes it refuses if a server answers on
 * http://127.0.0.1:<PORT||OMNI_PORT||3000> (see scripts/lib/dataDir.mjs), because
 * a running server holds its own copy and would overwrite this write.
 * `--force` skips that check. `--dry-run` writes nothing and skips it too.
 *
 * Usage:
 *   npx tsx scripts/reextract_meet_workspace.mjs --pdf <path> [--workspace <id>] [--dry-run] [--emit <json>] [--force]
 *
 * The source PDF is local-only, so this is not part of `npm test`.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Gender } from '../packages/core/src/types.ts';
import { resolveDataDir, assertNoServerHoldsStore } from './lib/dataDir.mjs';
import { mapAthleteRows } from '../apps/shell/lib/routes/parsingPipeline.ts';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA_DIR = resolveDataDir();
const MEETS_FILE = join(DATA_DIR, 'meets.json');
const PARSE_MEET = join(repoRoot, 'backend', 'parse_meet.py');

function arg(name) {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}
const DRY_RUN = process.argv.includes('--dry-run');
const FORCE = process.argv.includes('--force');
const pdfPath = arg('--pdf');
const workspaceId = arg('--workspace');

if (!pdfPath) {
  console.error('Usage: npx tsx scripts/reextract_meet_workspace.mjs --pdf <path> [--workspace <id>] [--dry-run]');
  process.exit(1);
}
if (!existsSync(pdfPath)) {
  console.error(`PDF not found: ${pdfPath}`);
  process.exit(1);
}

console.log(`meets.json: ${MEETS_FILE}${process.env.OMNI_DATA_DIR ? ' (OMNI_DATA_DIR)' : ' (default repo data/ -- the real store)'}`);

// --- 1. locate the workspace --------------------------------------------------
const workspaces = JSON.parse(readFileSync(MEETS_FILE, 'utf8'));
const pdfName = basename(pdfPath);
const matches = workspaces.filter(w =>
  workspaceId ? w.id === workspaceId : w.loadedMeet?.pdfFilename === pdfName
);
if (matches.length !== 1) {
  console.error(
    `Expected exactly one workspace for ${workspaceId ? `id ${workspaceId}` : `pdfFilename ${pdfName}`}, found ${matches.length}. ` +
      'Pass --workspace <id> to name one.'
  );
  process.exit(1);
}
const ws = matches[0];
const oldMen = ws.menResults ?? [];
const oldWomen = ws.womenResults ?? [];

// --- 2. refuse to orphan an id reference -------------------------------------
// Any field outside the four result arrays that quotes a result-row id would
// stop resolving the moment that row is regenerated. Preserving ids (step 5)
// covers rows that survive, but a reference to a row this parse no longer emits
// cannot be preserved, so stop and let a human decide.
const oldIds = new Set([...oldMen, ...oldWomen].map(r => r.id));
const otherFields = JSON.stringify(
  Object.fromEntries(
    Object.entries(ws).filter(
      ([k]) => !['menResults', 'womenResults', 'sourceMenResults', 'sourceWomenResults'].includes(k)
    )
  )
);
const referenced = [...oldIds].filter(id => otherFields.includes(id));

// --- 3. run the pipeline ------------------------------------------------------
function python(args, opts = {}) {
  for (const exe of ['python', 'python3', 'py']) {
    const run = spawnSync(exe, args, { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024, ...opts });
    if (run.error) continue;
    return run;
  }
  return null;
}

const run = python([PARSE_MEET, pdfPath, 'auto'], { cwd: join(repoRoot, 'backend') });
if (!run || run.status !== 0) {
  console.error('parse_meet.py failed');
  console.error(run?.stdout?.slice(0, 2000) ?? '');
  console.error(run?.stderr?.slice(0, 4000) ?? '');
  process.exit(1);
}
if (run.stderr?.trim()) {
  // The parser reports a leg it could not read on stderr. Surface it: the whole
  // point of this script is that a quiet loss becomes a wrong lineup later.
  console.log('--- parser warnings ---');
  console.log(run.stderr.trim());
  console.log('--- end parser warnings ---');
}
const parsed = JSON.parse(run.stdout.trim());
if (parsed.error) {
  console.error(`parse_meet.py: ${parsed.error}`);
  process.exit(1);
}

// --- 4. map rows with the server's own mapper -------------------------------
// `mapAthleteRows` throws ParsedRowError on a row it cannot map without guessing
// (bad rank, missing gender, non-numeric points). Let that stop the script: a
// re-extract must not write defaulted rows into the committed fixture.
const freshRows = mapAthleteRows(Array.isArray(parsed.athletes) ? parsed.athletes : []);

// --- 5. keep the id of any row that already existed --------------------------
// Identity is what the row says about the swim, not where it sits in the array.
// Relay rows are one per leg, so the leg index is part of it.
const identity = r =>
  JSON.stringify([
    r.gender, r.event, r.roundSwam ?? null, r.name, r.team, r.rank ?? 0,
    r.prelimsTime ?? null, r.finalsTime ?? null, Boolean(r.isRelay), r.relayLegIndex ?? null,
  ]);

const pool = new Map();
for (const r of [...oldMen, ...oldWomen]) {
  const k = identity(r);
  if (!pool.has(k)) pool.set(k, []);
  pool.get(k).push(r.id);
}
let reused = 0;
for (const r of freshRows) {
  const bucket = pool.get(identity(r));
  if (bucket && bucket.length > 0) {
    r.id = bucket.shift();
    reused += 1;
  }
}
const droppedIds = [...pool.values()].flat();
const brokenRefs = referenced.filter(id => droppedIds.includes(id));
if (brokenRefs.length > 0) {
  console.error(
    `Refusing to write: ${brokenRefs.length} result-row id(s) are referenced elsewhere in the ` +
      'workspace but no longer exist in the fresh parse. Resolve those overlays by hand first.'
  );
  for (const id of brokenRefs.slice(0, 10)) console.error(`  ${id}`);
  process.exit(1);
}

const men = freshRows.filter(r => r.gender === Gender.MEN);
const women = freshRows.filter(r => r.gender === Gender.WOMEN);

// --- 6. report -----------------------------------------------------------------
console.log(`workspace: ${ws.name} (${ws.id})`);
console.log(`  men:   ${oldMen.length} -> ${men.length}`);
console.log(`  women: ${oldWomen.length} -> ${women.length}`);
console.log(`  row ids preserved: ${reused} / ${freshRows.length} (new: ${freshRows.length - reused}, gone: ${droppedIds.length})`);
console.log(`  result ids referenced by other fields: ${referenced.length}`);
console.log(`  officialTeamScores: ${JSON.stringify(parsed.officialTeamScores)}`);

const emitPath = arg('--emit');
if (emitPath) {
  // The mapped rows, for checking a change before it is written.
  writeFileSync(emitPath, JSON.stringify(freshRows, null, 2), 'utf8');
  console.log(`  mapped rows written to ${emitPath}`);
}

if (DRY_RUN) {
  console.log(`dry run — ${MEETS_FILE} not written`);
  process.exit(0);
}

await assertNoServerHoldsStore({
  force: FORCE,
  what: DATA_DIR,
  fail: msg => {
    console.error(`ERROR: ${msg}`);
    process.exit(1);
  },
});

// --- 7. write the five fields, and prove nothing else moved -------------------
const before = JSON.parse(readFileSync(MEETS_FILE, 'utf8'));
ws.menResults = men;
ws.womenResults = women;
ws.sourceMenResults = JSON.parse(JSON.stringify(men));
ws.sourceWomenResults = JSON.parse(JSON.stringify(women));
if (parsed.officialTeamScores) ws.officialTeamScores = parsed.officialTeamScores;

const WRITTEN = new Set([
  'menResults', 'womenResults', 'sourceMenResults', 'sourceWomenResults', 'officialTeamScores',
]);
const beforeWs = before.find(w => w.id === ws.id);
const changedElsewhere = [];
for (const key of new Set([...Object.keys(beforeWs), ...Object.keys(ws)])) {
  if (WRITTEN.has(key)) continue;
  if (JSON.stringify(beforeWs[key]) !== JSON.stringify(ws[key])) changedElsewhere.push(key);
}
for (const w of before) {
  if (w.id === ws.id) continue;
  const now = workspaces.find(x => x.id === w.id);
  if (JSON.stringify(w) !== JSON.stringify(now)) changedElsewhere.push(`workspace:${w.id}`);
}
if (changedElsewhere.length > 0) {
  console.error(`Refusing to write: fields outside the meet results changed: ${changedElsewhere.join(', ')}`);
  process.exit(1);
}

writeFileSync(MEETS_FILE, JSON.stringify(workspaces, null, 2), 'utf8');
console.log(`${MEETS_FILE} updated`);
