/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * A workspace should take its name from the meet loaded into it.
 *
 * The bug this addresses: the live workspace holding the 2026 NSISC
 * Championships was called "Blank Workspace 1" (and was not blank), while the
 * one named "HSU 2026-27 Roster Plan" held no meet at all. Anyone opening the
 * app cold read the two backwards.
 *
 * The rule that matters most here is the negative one: a name the USER typed is
 * never overwritten, and a filename that yields nothing usable leaves the name
 * alone rather than inventing something.
 *
 * Test: npx tsx scripts/test_workspace_naming.mjs
 */
import assert from 'node:assert/strict';
import {
  isAutoGeneratedWorkspaceName,
  meetNameFromPdfFilename,
  workspaceNameForLoadedMeet,
} from '../packages/core/src/lib/workspaceNaming.ts';

// --- 1. Which names are the app's, and which are the user's? ----------------
{
  for (const auto of [
    'Blank Workspace 1',
    'Blank Workspace 12',
    'blank workspace',
    'New Workspace',
    'Workspace 3',
    'Untitled',
    'Untitled Workspace 2',
    '',
    '   ',
    undefined,
    null,
  ]) {
    assert.equal(isAutoGeneratedWorkspaceName(auto), true, `${JSON.stringify(auto)} is a placeholder`);
  }

  for (const chosen of [
    'HSU 2026-27 Roster Plan',
    'Conference champs',
    'Blank Workspace for Dana', // contains the words but is clearly deliberate
    '2026 NSISC Championships',
    'My Workspace 1',
  ]) {
    assert.equal(isAutoGeneratedWorkspaceName(chosen), false, `${JSON.stringify(chosen)} is user-chosen`);
  }
}

// --- 2. A readable meet name from the filename the operator picked ----------
{
  assert.equal(
    meetNameFromPdfFilename('2026_NSISC_Championships_Final_Results.pdf'),
    '2026 NSISC Championships'
  );
  assert.equal(meetNameFromPdfFilename('2026-Conference-Meet-Results.pdf'), '2026 Conference');
  assert.equal(meetNameFromPdfFilename('Spring Invite.pdf'), 'Spring Invite');
  // A browser may hand back a path; only the basename is a name.
  assert.equal(meetNameFromPdfFilename('C:\\Users\\x\\Downloads\\Winter_Open.pdf'), 'Winter Open');
  assert.equal(meetNameFromPdfFilename('/home/x/Winter_Open.pdf'), 'Winter Open');
  // Acronyms are preserved — title-casing would produce "Nsisc".
  assert.ok(meetNameFromPdfFilename('NSISC_2026.pdf').includes('NSISC'));
}

// --- 3. Nothing usable => no name, never a guess ---------------------------
{
  for (const useless of ['results.pdf', 'final results.pdf', 'FINAL.pdf', '2026.pdf', 'a.pdf', '.pdf', '', undefined, null]) {
    assert.equal(
      meetNameFromPdfFilename(useless),
      null,
      `${JSON.stringify(useless)} yields no usable name`
    );
  }
}

// --- 4. The decision function ----------------------------------------------
{
  // Placeholder + usable filename => rename.
  assert.equal(
    workspaceNameForLoadedMeet('Blank Workspace 1', '2026_NSISC_Championships_Final_Results.pdf', 'NSISC'),
    '2026 NSISC Championships',
    'conference already in the filename is not appended twice'
  );

  // Conference appended only when the filename does not already say it.
  assert.equal(
    workspaceNameForLoadedMeet('Blank Workspace 1', 'Spring_Invite.pdf', 'NSISC'),
    'Spring Invite (NSISC)'
  );

  // No conference detected => just the filename-derived name.
  assert.equal(workspaceNameForLoadedMeet('Blank Workspace 2', 'Spring_Invite.pdf', undefined), 'Spring Invite');

  // A user-chosen name is NEVER overwritten. This is the assertion that protects
  // the operator's own labelling.
  assert.equal(
    workspaceNameForLoadedMeet('HSU 2026-27 Roster Plan', '2026_NSISC_Championships.pdf', 'NSISC'),
    null
  );

  // Placeholder but nothing usable in the filename => leave it alone.
  assert.equal(workspaceNameForLoadedMeet('Blank Workspace 1', 'results.pdf', 'NSISC'), null);

  // Already correctly named => no redundant rename.
  assert.equal(
    workspaceNameForLoadedMeet('Spring Invite', 'Spring_Invite.pdf', undefined),
    null
  );
}

console.log('workspace naming: all assertions passed');
